name: quotify
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.11.0
  get_it: ^4.0.2
  flutter_bloc: ^4.0.1
  dartz: ^0.9.1
  dio: ^3.0.9
  data_connection_checker: ^0.3.4
  cupertino_icons: ^0.1.3
  equatable: ^1.2.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.11
  google_fonts: ^1.1.0
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_slidable: ^0.5.4
  flushbar: ^1.10.4

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.0
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
  assets:
    - images/failure.png
    - images/inspirational.png
    - images/love.png
    - images/nature.png
    - images/smile.png
    - images/nointernet.png
  fonts:
    - family: KS
      fonts:
        - asset: fonts/KS-Regular.ttf
